package me.devamy.contracts.utils;

import me.devamy.contracts.Contracts;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

public class WikiGenerator {

    private final StringBuilder sb = new StringBuilder();

    public static void generate() {
        final WikiGenerator gen = new WikiGenerator();
        gen.build();
        gen.write();
    }

    private void build() {
        line("╔══════════════════════════════════════════════════════════════════════╗");
        line("║                        Dcontracts — Plugin Wiki                      ║");
        line("╚══════════════════════════════════════════════════════════════════════╝");
        line("");
        line("  Version: " + Contracts.plugin.getPluginMeta().getVersion());
        line("  Author:  " + Contracts.plugin.getPluginMeta().getAuthors());
        line("  Wiki:    https://github.com/DevAmy/Dcontracts/wiki");
        line("");
        line("  This file gets regenerated every time the plugin starts up, so it");
        line("  always matches whatever version you're running. Don't bother editing");
        line("  it by hand — your changes will be overwritten.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  1. WHAT IS DCONTRACTS?");
        line("");
        line("  Dcontracts lets players on your server request items from other");
        line("  players and pay them for it. Think of it like a reversed auction");
        line("  house — instead of selling stuff, you post a contract saying \"I need");
        line("  64 diamonds, I'll pay $100 each,\" and other players fill that contract");
        line("  by delivering the items.");
        line("");
        line("  Features at a glance:");
        line("    - Create contracts requesting specific items");
        line("    - Other players deliver to fulfill them and get paid");
        line("    - Collect delivered items from your contracts");
        line("    - Cancel contracts and get refunded");
        line("    - Admin GUI for managing everything");
        line("    - Item blacklist + custom item support (ItemsAdder, Nexo, etc.)");
        line("    - SQLite, MySQL, or H2 storage");
        line("    - GeyserMC/Floodgate (Bedrock) support");
        line("    - Folia compatible");
        line("    - Pretty much everything is configurable");
        line("    - Developer API with custom events");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  2. REQUIREMENTS");
        line("");
        line("  You need these (required):");
        line("    - Paper 1.21.7+ (or Purpur/Pufferfish/Folia)");
        line("    - Vault or VaultUnlocked");
        line("    - An economy plugin (EssentialsX, CMI, whatever)");
        line("    - packetevents (https://modrinth.com/plugin/packetevents)");
        line("");
        line("  Optional:");
        line("    - GeyserMC + Floodgate (for Bedrock players)");
        line("");
        line("  Won't work with:");
        line("    - Cross-server setups (no Bungee/Velocity data sharing)");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  3. INSTALLATION");
        line("");
        line("  1. Drop the jar in plugins/");
        line("  2. Make sure Vault + an economy plugin + packetevents are installed");
        line("  3. (Optional) Install GeyserMC + Floodgate for Bedrock support");
        line("  4. Start the server — config files generate automatically");
        line("  5. Edit config files to your liking");
        line("  6. /contracts admin reload to apply changes without restarting");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  4. COMMANDS");
        line("");
        line("  /contracts              Open the main GUI");
        line("  /contracts <search>     Open the main GUI filtered by a search term");
        line("  /contracts create       Jump straight to contract creation");
        line("  /contracts admin        Admin panel (GUI for players, text for console)");
        line("  /contracts admin reload          Reload all configs");
        line("  /contracts admin blacklist       Blacklist editor (in-game)");
        line("  /contracts admin custom_items    Custom items editor (in-game)");
        line("  /contracts admin convert         Database converter (in-game)");
        line("");
        line("  Aliases: /contract and /c both open the main GUI");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  5. PERMISSIONS");
        line("");
        line("  contracts.use                           default: true");
        line("    Use /contracts and open the main GUI");
        line("");
        line("  contracts.create                        default: true");
        line("    Create new contracts");
        line("");
        line("  contracts.admin                         default: op");
        line("    Access /contracts admin and the admin GUI");
        line("");
        line("  contracts.admin.blacklist               default: op");
        line("    Manage the item blacklist");
        line("");
        line("  contracts.admin.custom-items            default: op");
        line("    Manage custom items");
        line("");
        line("  contracts.admin.edit-contracts          default: op");
        line("    Edit anyone's contracts from the admin GUI");
        line("");
        line("  contracts.admin.delete-contracts        default: op");
        line("    Delete anyone's contracts (force-delete, no refund)");
        line("");
        line("  contracts.admin.reload                  default: op");
        line("    Reload the plugin config");
        line("");
        line("  contracts.admin.convert                 default: op");
        line("    Run the database converter");
        line("");
        line("  contracts.bypass.tax                    default: op");
        line("    Skip the tax on deliveries");
        line("");
        line("  contracts.bypass.max-collect            default: op");
        line("    Bypass the max-collect limit");
        line("");
        line("  contracts.bypass.max-collect-per-minute default: op");
        line("    Bypass the rate limit on collecting");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  6. CONFIG FILES");
        line("");
        line("  All files live in plugins/Dcontracts/:");
        line("");
        line("  config.yml          General settings, sounds, sorts, status text");
        line("  messages.yml        All player-facing messages (MiniMessage format)");
        line("  database.yml        Database connection settings");
        line("");
        line("  gui/ subdirectory — each GUI has its own file:");
        line("    main.yml              Main contracts browser");
        line("    your-contracts.yml    Your own contracts");
        line("    choose-item.yml       Item picker");
        line("    search.yml            Search sign");
        line("    enchant.yml           Enchantment GUI (disabled by default)");
        line("    deliver.yml           Delivery inventory");
        line("    new-contract-dialog.yml    New contract dialog");
        line("    confirm-delivery.yml      Delivery confirmation dialog");
        line("    manage-contract.yml       Manage contract dialog");
        line("    admin.yml            Admin panel");
        line("");
        line("  When you update the plugin, new config keys get merged in");
        line("  automatically — your existing values and comments stay untouched.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  7. config.yml");
        line("");
        line("  config-version         (internal, don't touch)");
        line("  bstats                 true/false — anonymous stats via bStats");
        line("  check-for-updates      true/false — check Modrinth on startup");
        line("  log-transactions       true/false — log Vault transactions to console");
        line("  expires-after          milliseconds before a contract expires");
        line("                         default: 604800000 (7 days)");
        line("  minimum-price          minimum price per item (default: 0.1)");
        line("  max-collect            max items collected from one contract at once");
        line("                         default: 1000");
        line("  max-collect-per-minute global rate limit across all contracts");
        line("                         default: 1000");
        line("  shulker-delivering     true/false — let players deliver via shulkers");
        line("  broadcast-contract-creation");
        line("                         true/false — announce new contracts globally");
        line("  parallel-processing    true/false — parallel ops on Paper/Purpur/Folia");
        line("");
        line("  similarity-check:");
        line("    A list of data components used to decide if two items are \"the same\"");
        line("    for delivery matching. If all listed components match, items count as");
        line("    identical regardless of type. Defaults cover most common cases:");
        line("      minecraft:enchantments, minecraft:bundle_contents,");
        line("      minecraft:container, minecraft:fireworks, minecraft:instrument,");
        line("      minecraft:potion_contents, minecraft:stored_enchantments,");
        line("      minecraft:max_stack_size, minecraft:custom_model_data,");
        line("      minecraft:ominous_bottle_amplifier, minecraft:damage,");
        line("      minecraft:custom_name, minecraft:item_model,");
        line("      minecraft:damage_type, minecraft:consumable");
        line("    Ref: https://minecraft.wiki/w/Data_component_format");
        line("");
        line("  sorts-display:");
        line("    Controls how sort options show up in GUIs. Each sort has an");
        line("    'active' (selected) and 'inactive' (not selected) display string.");
        line("    Available sorts: most-money-per-item, recently-listed,");
        line("    most-delivered, most-paid, a-z, z-a, priciest, cheapest, oldest");
        line("");
        line("  contract-status:");
        line("    Text shown for each contract state. Supports MiniMessage +");
        line("    placeholders: <day>, <hour>, <minute>, <second>");
        line("    States: available, expired, completed");
        line("");
        line("  sounds:");
        line("    Each sound entry has: sound (namespaced key), volume (0-1), pitch");
        line("    Entries: next-page, previous-page, refresh, sort, new-contract,");
        line("    deliver");
        line("    Sound names: https://minecraft.wiki/w/Sounds.json");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  8. messages.yml");
        line("");
        line("  All player-facing messages. MiniMessage format supported everywhere.");
        line("");
        line("  create-contract-success");
        line("    \"<gray>Your contract has been created\"");
        line("    Shown after creating a contract");
        line("");
        line("  invalid-input");
        line("    \"<red>Invalid number or format\"");
        line("    When someone types gibberish in a dialog");
        line("");
        line("  deliver");
        line("    \"<gray>You earned <green>$<money><gray> from delivering a contract\"");
        line("    Sent to the deliverer. Placeholder: <money>");
        line("");
        line("  receive-delivery");
        line("    \"<aqua><deliverer> <gray>delivered you <aqua><amount> <item>\"");
        line("    Sent to the contract owner. Placeholders: <deliverer>, <amount>,");
        line("    <item>");
        line("");
        line("  not-enough-money");
        line("    \"<red>You do not have enough money\"");
        line("    When the player can't afford it");
        line("");
        line("  deliver-self");
        line("    \"<red>You cannot deliver your own contract\"");
        line("    Self-explanatory");
        line("");
        line("  exceeded-max-collect");
        line("    \"<red>You are collecting too many items\"");
        line("    Hit the max-collect limit");
        line("");
        line("  collecting-too-fast");
        line("    \"<red>You are collecting items too fast. Wait a minute...\"");
        line("    Hit the max-collect-per-minute rate limit");
        line("");
        line("  contract-creation-broadcast");
        line("    \"<green><player> <white>has just created a new contract for");
        line("    <green><item> <white>in <gray>/contracts\"");
        line("    Broadcast when someone makes a contract (if enabled).");
        line("    Placeholders: <player>, <item>");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  9. database.yml");
        line("");
        line("  storage-method     SQLITE | MYSQL | H2 (default: SQLITE)");
        line("                     SQLITE needs nothing else. MYSQL connects to an");
        line("                     external server. H2 is embedded (file-based).");
        line("");
        line("  host               MySQL host (default: localhost)");
        line("  port               MySQL port (default: 3306)");
        line("  database           MySQL database name (default: dcontracts)");
        line("  username           MySQL user (default: root)");
        line("  password           MySQL password (default: empty)");
        line("");
        line("  pool-settings:     HikariCP connection pool tuning");
        line("    maximum-pool-size        default: 10");
        line("    minimum-idle             default: 2");
        line("    connection-timeout (ms)  default: 5000");
        line("    idle-timeout (ms)        default: 600000 (10 min)");
        line("    max-lifetime (ms)        default: 1800000 (30 min)");
        line("");
        line("  Database files:");
        line("    SQLite: plugins/Dcontracts/data.db");
        line("    H2:     plugins/Dcontracts/data-h2.*");
        line("");
        line("  Use /contracts admin convert to migrate between storage methods.");
        line("  It copies orders, transactions, custom items, and the blacklist.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  10. GUI CONFIGS");
        line("");
        line("  Each GUI file under gui/ has its own settings. All text supports");
        line("  MiniMessage. Common patterns:");
        line("");
        line("  gui/main.yml — Main contracts browser");
        line("    title, rows, contract.slots, contract.lore, contract.item");
        line("    sorts-order (which sorts to show and in what order)");
        line("    buttons: refresh, your-contracts, sort, search, back, next");
        line("    Lore placeholders: <paid>, <total>, <delivered>, <amount>,");
        line("    <money-per>, <player>");
        line("");
        line("  gui/your-contracts.yml — Your own contracts");
        line("    title, rows, contract.slots, contract.lore, contract.item");
        line("    buttons: new-contract");
        line("    Extra placeholder: <contract-status>");
        line("");
        line("  gui/choose-item.yml — Item picker");
        line("    title, rows, slots, sorts-order");
        line("    buttons: sort, back, next, search");
        line("");
        line("  gui/search.yml — Search sign");
        line("    type (sign block type), query-line (0-3), lines (4 default lines)");
        line("");
        line("  gui/enchant.yml — Enchantment GUI (off by default)");
        line("    enabled, title, rows, display-item-slot");
        line("    enchantment-book: name.active, name.inactive, item, slots");
        line("    Name placeholders: <enchantment>, <roman-numeral-level>");
        line("    buttons: confirm");
        line("");
        line("  gui/deliver.yml — Delivery inventory");
        line("    title, rows");
        line("");
        line("  gui/new-contract-dialog.yml — New contract dialog");
        line("    title, can-close-with-escape, body (description, width,");
        line("    show-decoration, show-tooltip, dimensions)");
        line("    inputs: amount, money-per-item (label, width, initial, max_length,");
        line("    label_visible)");
        line("    buttons: confirm, change-item (label, tooltip, width)");
        line("");
        line("  gui/confirm-delivery.yml — Delivery confirmation");
        line("    title, can-close-with-escape");
        line("    bodies: text, transaction (contents, width)");
        line("    Placeholders: <amount>, <money>");
        line("    buttons: confirm, cancel");
        line("");
        line("  gui/manage-contract.yml — Manage your contract");
        line("    manage-contract: title, can-close-with-escape, buttons");
        line("    collect-items: title, body, amount-input, buttons");
        line("    cancel-contract: title, body, buttons");
        line("    Placeholders: <in-storage>, <item>");
        line("");
        line("  gui/admin.yml — Admin panel");
        line("    title, rows, contract-item.slots, contract-item.lore");
        line("    Extra placeholders: <id>, <in-storage>, <total>");
        line("    Interactions: left-click edit, right-click cancel (refund),");
        line("    shift+right-click force-delete (no refund)");
        line("    Buttons: sort, refresh, search, close, back, next, filter");
        line("");
        line("  Button item format (vanilla components):");
        line("    buttons.example:");
        line("      slot: 49");
        line("      item:");
        line("        components:");
        line("          minecraft:item_name: \"<!i><aqua>Name\"");
        line("          minecraft:lore: [\"<!i><white>Lore line\"]");
        line("        id: minecraft:paper");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  11. MINIMESSAGE");
        line("");
        line("  All text in Dcontracts uses MiniMessage. Common tags:");
        line("");
        line("    <red> <green> <aqua> <gray> <white> <yellow> <gold>  colors");
        line("    <dark_red> <dark_gray> <blue>                        more colors");
        line("    <#786500>                                             hex colors");
        line("    <!i>              remove italic (items are italic by default)");
        line("    <u>                underline");
        line("    <click:open_url:'URL'>text</click>   clickable link");
        line("");
        line("  Full docs: https://docs.advntr.dev/minimessage/format.html");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  12. ADMIN TOOLS");
        line("");
        line("  Blacklist (/contracts admin blacklist):");
        line("    Click an item to remove it. Place an item to add it.");
        line("    Blacklisted items can't be used in contracts.");
        line("");
        line("  Custom Items (/contracts admin custom_items):");
        line("    Register items from other plugins so players can find them.");
        line("    Place an item to register it. Left-click to edit search aliases.");
        line("    Right-click to get a copy. Shift+right-click to remove.");
        line("    Search aliases make items show up when players search by name.");
        line("");
        line("  Database Converter (/contracts admin convert):");
        line("    Pick source → pick target → enter credentials if needed.");
        line("    Transfers everything: orders, transactions, custom items, blacklist.");
        line("    Don't close the GUI or stop the server mid-conversion.");
        line("    Afterward, update database.yml and /contracts admin reload.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  13. DATA STORAGE");
        line("");
        line("  Tables created automatically:");
        line("    contracts_orders          all contracts");
        line("    contracts_transactions    money transaction log");
        line("    contracts_custom_items_v2 registered custom items + search aliases");
        line("    contracts_blacklist       blacklisted items");
        line("");
        line("  A separate SQLite db (modified_items.db) holds blacklist + custom");
        line("  items regardless of your chosen storage method.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  14. BEDROCK SUPPORT");
        line("");
        line("  If GeyserMC + Floodgate are installed, Bedrock players get");
        line("  container-based fallbacks for Paper dialogs (Java-only feature).");
        line("  No extra config needed — it just works.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  15. DEVELOPER API");
        line("");
        line("  Package: me.devamy.contracts.api");
        line("");
        line("  Order interface — me.devamy.contracts.api.Order");
        line("    getId()              int        contract ID");
        line("    getOwnerUniqueId()   UUID       owner's UUID");
        line("    getItem()            ItemStack  requested item");
        line("    getMoneyPer()        double     money per item");
        line("    getAmount()          int        total requested");
        line("    getDelivered()       int        delivered so far");
        line("    getInStorage()       int        items ready to collect");
        line("    getExpiresAt()       long       expiry epoch ms");
        line("    setDelivered(int)    void       update delivered count");
        line("    setInStorage(int)    void       update in-storage count");
        line("    setAmount(int)       void       update requested amount");
        line("    setMoneyPer(double)  void       update price per item");
        line("");
        line("  Events (all have Pre + Post, Pre is cancellable):");
        line("");
        line("    PlayerCreateOrderEvent");
        line("      Pre:  getPlayer(), getItem(), getMoneyPer(), getAmount()");
        line("      Post: getPlayer(), getOrder()");
        line("");
        line("    PlayerDeliverOrderEvent");
        line("      Pre:  getPlayer(), getOrder()");
        line("      Post: getPlayer(), getOrder()");
        line("");
        line("    PlayerCollectItemsEvent");
        line("      Pre:  getPlayer(), getOrder(), getAmount()");
        line("      Post: getPlayer(), getOrder(), getAmount()");
        line("");
        line("    PlayerCancelOrderEvent");
        line("      Pre:  getPlayer(), getOrder()");
        line("      Post: getPlayer(), getOrder()");
        line("");
        line("    OrderRemoveEvent");
        line("      Pre:  getOrder()");
        line("      Post: getOrder()");
        line("      Fired when a contract is cleaned up from memory");
        line("      (e.g. expired + empty, owner opens Your Contracts)");
        line("");
        line("  Example:");
        line("    @EventHandler");
        line("    public void onCreate(PlayerCreateOrderEvent.Post e) {");
        line("        Order o = e.getOrder();");
        line("        Player p = e.getPlayer();");
        line("        // do stuff");
        line("    }");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  16. METRICS");
        line("");
        line("  bStats + FastStats collect anonymous data. Disable with");
        line("  bstats: false in config.yml.");
        line("");
        line("  What's collected: API usage, experimental features in use,");
        line("  total contracts created, total items collected, error reports.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  17. TROUBLESHOOTING");
        line("");
        line("  \"No economy plugin found\"");
        line("    -> Install Vault/VaultUnlocked + an economy plugin (EssentialsX)");
        line("       Make sure they load before Dcontracts.");
        line("");
        line("  GUI is empty");
        line("    -> Check contracts.use permission. Check console for errors.");
        line("");
        line("  Delivery not working");
        line("    -> Check similarity-check config. Items must match all listed");
        line("       components. Make sure the contract hasn't expired.");
        line("");
        line("  MySQL connection failed");
        line("    -> Double-check host/port/db/user/pass in database.yml.");
        line("       Make sure the MySQL server is reachable from your MC server.");
        line("");
        line("  Bedrock players can't see dialogs");
        line("    -> Install GeyserMC + Floodgate. Fallback GUIs kick in");
        line("       automatically.");
        line("");
        line("  Items from other plugins don't show up");
        line("    -> Register them via /contracts admin custom_items and add");
        line("       search aliases so players can find them.");
        line("");
        line("──────────────────────────────────────────────────────────────────────────");
        line("");
        line("  End of wiki. This file is auto-generated — don't edit it.");
        line("");
    }

    private void line(String text) {
        sb.append(text).append("\n");
    }

    private void write() {
        final File wikiFile = new File(Contracts.plugin.getDataFolder(), "wiki.txt");
        try {
            Files.writeString(wikiFile.toPath(), sb.toString(), StandardCharsets.UTF_8);
            Log.info("wiki.txt generated at " + wikiFile.getAbsolutePath());
        } catch (IOException e) {
            Log.error("Failed to write wiki.txt", e);
        }
    }
}
