config-version: 7

bstats: true
check-for-updates: true
log-transactions: true
expires-after: 604800000
minimum-price: 0.1
max-collect: 1000
max-collect-per-minute: 1000
shulker-delivering: true
broadcast-contract-creation: false
parallel-processing: true

similarity-check:
  - "minecraft:enchantments"
  - "minecraft:bundle_contents"
  - "minecraft:container"
  - "minecraft:fireworks"
  - "minecraft:instrument"
  - "minecraft:potion_contents"
  - "minecraft:stored_enchantments"
  - "minecraft:max_stack_size"
  - "minecraft:custom_model_data"
  - "minecraft:ominous_bottle_amplifier"
  - "minecraft:damage"
  - "minecraft:custom_name"
  - "minecraft:item_model"
  - "minecraft:damage_type"
  - "minecraft:consumable"

sorts-display:
  active:
    most-money-per-item: "<aqua>Most Money Per Item"
    recently-listed: "<aqua>Recently Listed"
    most-delivered: "<aqua>Most Delivered"
    most-paid: "<aqua>Most Paid"
    a-z: "<aqua>A - Z"
    z-a: "<aqua>Z - A"
    priciest: "<aqua>Priciest"
    cheapest: "<aqua>Cheapest"
    oldest: "<aqua>Oldest"
  inactive:
    most-money-per-item: "Most Money Per Item"
    recently-listed: "Recently Listed"
    most-delivered: "Most Delivered"
    most-paid: "Most Paid"
    a-z: "A - Z"
    z-a: "Z - A"
    priciest: "Priciest"
    cheapest: "Cheapest"
    oldest: "Oldest"

contract-status:
  available: "<gray>Expires after <day>d <hour>h <minute>m <second>s"
  expired: "<red>Contract Expired"
  completed: "<green>Contract Completed"

sounds:
  next-page:
    sound: "minecraft:ui.button.click"
    volume: 1.0
    pitch: 1.0
  previous-page:
    sound: "minecraft:ui.button.click"
    volume: 1.0
    pitch: 1.0
  refresh:
    sound: "minecraft:ui.button.click"
    volume: 1.0
    pitch: 1.0
  sort:
    sound: "minecraft:ui.button.click"
    volume: 1.0
    pitch: 1.0
  new-contract:
    sound: "minecraft:entity.villager.work_cartographer"
    volume: 1.0
    pitch: 1.0
  deliver:
    sound: "minecraft:entity.player.levelup"
    volume: 1.0
    pitch: 2.0
